[package]
name = "cpcodec"
version = "0.0.0"
edition = "2021"

[lib]
name = "cpcodec"
crate-type = ["dylib"]

[dependencies]
half = { workspace = true, features = ["std"] }
libc = { workspace = true }
pco = { version = "1.0.0", path = "../pco" }
